# Generated by Django 4.2.13 on 2026-06-02 20:41

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('file_format', models.CharField(help_text='e.g., CSV, JSON, HDF5, NetCDF', max_length=50)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private - Only Owner'), ('peer_review', 'Peer Reviewers Only'), ('public', 'Public')], default='private', max_length=20)),
                ('data_file', cloudinary.models.CloudinaryField(help_text='Uploaded dataset file', max_length=255, verbose_name='dataset')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-creation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Professional biography', null=True)),
                ('institution', models.CharField(blank=True, help_text='University/Research Institution', max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, help_text='Job title/Position', max_length=100)),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID identifier', max_length=50, unique=True)),
                ('google_scholar', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('research_interests', models.TextField(blank=True, help_text='Comma-separated research areas')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('admin', 'Administrator')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Researcher Profile',
                'verbose_name_plural': 'Researcher Profiles',
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(help_text='Research abstract - always visible')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('peer_review', 'Under Peer Review'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private - Only Owner'), ('peer_review', 'Peer Reviewers Only'), ('institution', 'Institution Members'), ('public', 'Public')], default='private', max_length=20)),
                ('pdf_file', cloudinary.models.CloudinaryField(help_text='Full research paper PDF', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='paper_pdf')),
                ('supplementary_data', cloudinary.models.CloudinaryField(blank=True, help_text='Supplementary materials/datasets', max_length=255, null=True, verbose_name='supplementary')),
                ('raw_data_file', cloudinary.models.CloudinaryField(blank=True, help_text='Raw experimental data - restricted access', max_length=255, null=True, verbose_name='raw_data')),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='portfolio.researcherprofile')),
            ],
            options={
                'verbose_name': 'Research Paper',
                'verbose_name_plural': 'Research Papers',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('preview', 'Preview')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.dataset')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.researchpaper')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Access Log',
                'verbose_name_plural': 'File Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='portfolio.researchpaper'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='portfolio.researcherprofile'),
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('author_institution', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Author order in publication')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='portfolio.researchpaper')),
            ],
            options={
                'verbose_name': 'Co-Author',
                'verbose_name_plural': 'Co-Authors',
                'ordering': ['paper', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('view_abstract', 'View Abstract Only'), ('view_full', 'View Full Paper'), ('download', 'Download Paper'), ('view_raw_data', 'View Raw Data'), ('download_raw_data', 'Download Raw Data')], max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent access', null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='portfolio.dataset')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='portfolio.researchpaper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_access_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Permission',
                'verbose_name_plural': 'Access Permissions',
            },
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['researcher', 'visibility', 'status'], name='portfolio_r_researc_ecd9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['doi'], name='portfolio_r_doi_7a0cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['created_at'], name='portfolio_r_created_a7ac24_idx'),
        ),
        migrations.AddIndex(
            model_name='researcherprofile',
            index=models.Index(fields=['user', 'tier'], name='portfolio_r_user_id_d422b0_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='portfolio_f_user_id_79378a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['paper', 'accessed_at'], name='portfolio_f_paper_i_aa602a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['dataset', 'accessed_at'], name='portfolio_f_dataset_c5e486_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['researcher', 'visibility'], name='portfolio_d_researc_749cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['created_at'], name='portfolio_d_created_d2e11d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coauthor',
            unique_together={('paper', 'order')},
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['reviewer', 'is_active'], name='portfolio_a_reviewe_3ec5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['granted_at'], name='portfolio_a_granted_6cc4f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accesspermission',
            unique_together={('paper', 'dataset', 'reviewer', 'permission_type')},
        ),
    ]
